image: Visual Studio 2017
version: '1.0.{build}'

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release

# restore NuGet packages before running MSBuild
before_build:
  - appveyor-retry dotnet restore -v Minimal
  
# package Web Application project for Web Deploy
build:
  project: Blue.sln
  verbosity: minimal
  publish_wap: true

test: off
deploy: off
