image: Visual Studio 2017
version: '1.0.{build}'

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x86
      configuration: Release
      
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  - cmd: cd blue.api
  
# package Web Application project for Web Deploy
build:
  verbosity: minimal
  publish_wap: true

test: off
