configuration: Release
version: '1.0.{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  
# package Web Application project for Web Deploy
build:
  verbosity: minimal
  publish_wap: true
